//! Built-in provider descriptors and the generated Pi model catalog.
//!
//! The embedded catalog is generated by Pi's own `generate-model-catalog`
//! command. Dynamic/custom endpoints remain explicit constructors.

use std::{
    collections::{BTreeMap, BTreeSet},
    sync::{Arc, OnceLock},
};

use async_trait::async_trait;
use bytes::Bytes;
use parking_lot::RwLock;
use serde::Deserialize;
use url::Url;

use crate::{
    auth::{AuthResult, EnvApiKeyAuth, ProviderAuth},
    error::AiError,
    message::Context,
    model::{ImageModel, Model, ModelCost, ModelCostRates, ModelInput, ThinkingLevel},
    provider::{Provider, ProviderDescriptor, RefreshOptions},
    stream::AssistantEventStream,
    transport::{DynHttpTransport, HttpHeaders, HttpRequest, ReqwestTransport},
    wire::{
        WireAdapter, WireRequestOptions,
        anthropic::AnthropicMessagesAdapter,
        bedrock::BedrockConverseStreamAdapter,
        execute_text_stream,
        google::{GoogleGenerativeAiAdapter, GoogleVertexAdapter},
        mistral::MistralConversationsAdapter,
        openai::{
            AzureOpenAiResponsesAdapter, OpenAiCodexAdapter, OpenAiCompletionsAdapter,
            OpenAiResponsesAdapter,
        },
        pi_messages::PiMessagesAdapter,
    },
};

type ModelCatalog = BTreeMap<String, BTreeMap<String, Model>>;

static MODEL_CATALOG: OnceLock<ModelCatalog> = OnceLock::new();

#[derive(Clone, Copy)]
struct ProviderSpec {
    id: &'static str,
    name: &'static str,
    auth_name: &'static str,
    auth_variables: &'static [&'static str],
}

const STATIC_PROVIDER_SPECS: &[ProviderSpec] = &[
    provider(
        "amazon-bedrock",
        "Amazon Bedrock",
        "Amazon Bedrock bearer token",
        &["AWS_BEARER_TOKEN_BEDROCK"],
    ),
    provider(
        "ant-ling",
        "Ant Ling",
        "Ant Ling API key",
        &["ANT_LING_API_KEY"],
    ),
    provider(
        "anthropic",
        "Anthropic",
        "Anthropic API key",
        &["ANTHROPIC_API_KEY"],
    ),
    provider(
        "azure-openai-responses",
        "Azure OpenAI",
        "Azure OpenAI API key",
        &["AZURE_OPENAI_API_KEY"],
    ),
    provider(
        "cerebras",
        "Cerebras",
        "Cerebras API key",
        &["CEREBRAS_API_KEY"],
    ),
    provider(
        "cloudflare-ai-gateway",
        "Cloudflare AI Gateway",
        "Cloudflare API key",
        &["CLOUDFLARE_API_KEY"],
    ),
    provider(
        "cloudflare-workers-ai",
        "Cloudflare Workers AI",
        "Cloudflare API key",
        &["CLOUDFLARE_API_KEY"],
    ),
    provider(
        "deepseek",
        "DeepSeek",
        "DeepSeek API key",
        &["DEEPSEEK_API_KEY"],
    ),
    provider(
        "fireworks",
        "Fireworks",
        "Fireworks API key",
        &["FIREWORKS_API_KEY"],
    ),
    provider(
        "github-copilot",
        "GitHub Copilot",
        "GitHub Copilot token",
        &["COPILOT_GITHUB_TOKEN"],
    ),
    provider("google", "Google", "Gemini API key", &["GEMINI_API_KEY"]),
    provider(
        "google-vertex",
        "Google Vertex AI",
        "Google Cloud API key",
        &["GOOGLE_CLOUD_API_KEY"],
    ),
    provider("groq", "Groq", "Groq API key", &["GROQ_API_KEY"]),
    provider(
        "huggingface",
        "Hugging Face",
        "Hugging Face token",
        &["HF_TOKEN"],
    ),
    provider(
        "kimi-coding",
        "Kimi For Coding",
        "Kimi API key",
        &["KIMI_API_KEY"],
    ),
    provider(
        "minimax",
        "MiniMax",
        "MiniMax API key",
        &["MINIMAX_API_KEY"],
    ),
    provider(
        "minimax-cn",
        "MiniMax CN",
        "MiniMax CN API key",
        &["MINIMAX_CN_API_KEY"],
    ),
    provider(
        "mistral",
        "Mistral",
        "Mistral API key",
        &["MISTRAL_API_KEY"],
    ),
    provider(
        "moonshotai",
        "Moonshot AI",
        "Moonshot AI API key",
        &["MOONSHOT_API_KEY"],
    ),
    provider(
        "moonshotai-cn",
        "Moonshot AI CN",
        "Moonshot AI API key",
        &["MOONSHOT_API_KEY"],
    ),
    provider("nvidia", "NVIDIA", "NVIDIA API key", &["NVIDIA_API_KEY"]),
    provider("openai", "OpenAI", "OpenAI API key", &["OPENAI_API_KEY"]),
    provider(
        "openai-codex",
        "OpenAI Codex",
        "OpenAI Codex access token",
        &["OPENAI_CODEX_ACCESS_TOKEN"],
    ),
    provider(
        "opencode",
        "OpenCode Zen",
        "OpenCode API key",
        &["OPENCODE_API_KEY"],
    ),
    provider(
        "opencode-go",
        "OpenCode Zen Go",
        "OpenCode API key",
        &["OPENCODE_API_KEY"],
    ),
    provider(
        "openrouter",
        "OpenRouter",
        "OpenRouter API key",
        &["OPENROUTER_API_KEY"],
    ),
    provider(
        "qwen-token-plan",
        "Qwen Token Plan",
        "Qwen Token Plan API key",
        &["QWEN_TOKEN_PLAN_API_KEY"],
    ),
    provider(
        "qwen-token-plan-cn",
        "Qwen Token Plan CN",
        "Qwen Token Plan CN API key",
        &["QWEN_TOKEN_PLAN_CN_API_KEY"],
    ),
    provider(
        "together",
        "Together",
        "Together API key",
        &["TOGETHER_API_KEY"],
    ),
    provider(
        "vercel-ai-gateway",
        "Vercel AI Gateway",
        "Vercel AI Gateway API key",
        &["AI_GATEWAY_API_KEY"],
    ),
    provider("xai", "xAI", "xAI API key", &["XAI_API_KEY"]),
    provider("xiaomi", "Xiaomi", "Xiaomi API key", &["XIAOMI_API_KEY"]),
    provider(
        "xiaomi-token-plan-ams",
        "Xiaomi Token Plan AMS",
        "Xiaomi Token Plan AMS API key",
        &["XIAOMI_TOKEN_PLAN_AMS_API_KEY"],
    ),
    provider(
        "xiaomi-token-plan-cn",
        "Xiaomi Token Plan CN",
        "Xiaomi Token Plan CN API key",
        &["XIAOMI_TOKEN_PLAN_CN_API_KEY"],
    ),
    provider(
        "xiaomi-token-plan-sgp",
        "Xiaomi Token Plan SGP",
        "Xiaomi Token Plan SGP API key",
        &["XIAOMI_TOKEN_PLAN_SGP_API_KEY"],
    ),
    provider("zai", "Z.AI", "Z.AI API key", &["ZAI_API_KEY"]),
    provider(
        "zai-coding-cn",
        "Z.AI Coding CN",
        "Z.AI Coding CN API key",
        &["ZAI_CODING_CN_API_KEY"],
    ),
];

const fn provider(
    id: &'static str,
    name: &'static str,
    auth_name: &'static str,
    auth_variables: &'static [&'static str],
) -> ProviderSpec {
    ProviderSpec {
        id,
        name,
        auth_name,
        auth_variables,
    }
}

/// Returns every built-in text provider using the production reqwest transport.
pub fn builtin_providers() -> Vec<Arc<dyn Provider>> {
    let transport: DynHttpTransport = Arc::new(ReqwestTransport::default());
    let adapters = builtin_adapters();
    let mut providers = STATIC_PROVIDER_SPECS
        .iter()
        .map(|spec| {
            Arc::new(static_provider_with_adapters(
                spec,
                transport.clone(),
                &adapters,
            )) as Arc<dyn Provider>
        })
        .collect::<Vec<_>>();
    providers.push(Arc::new(RadiusProvider::new(
        "radius",
        "Radius",
        "https://radius.pi.dev",
        transport,
    )));
    providers
}

/// Flattens the static portion of the built-in text catalog.
pub fn builtin_models() -> Vec<Model> {
    model_catalog()
        .values()
        .flat_map(|models| models.values().cloned())
        .collect()
}

fn model_catalog() -> &'static ModelCatalog {
    MODEL_CATALOG.get_or_init(|| {
        serde_json::from_str(include_str!("model_catalog.generated.json"))
            .expect("generated Pi model catalog must deserialize")
    })
}

fn provider_models(provider_id: &str) -> Vec<Model> {
    model_catalog()
        .get(provider_id)
        .unwrap_or_else(|| panic!("generated Pi model catalog is missing provider {provider_id}"))
        .values()
        .cloned()
        .collect()
}

fn provider_spec(provider_id: &str) -> &'static ProviderSpec {
    STATIC_PROVIDER_SPECS
        .iter()
        .find(|spec| spec.id == provider_id)
        .unwrap_or_else(|| panic!("missing built-in provider specification for {provider_id}"))
}

fn static_provider(spec: &ProviderSpec, transport: DynHttpTransport) -> ProviderDescriptor {
    static_provider_with_adapters(spec, transport, &builtin_adapters())
}

fn static_provider_with_adapters(
    spec: &ProviderSpec,
    transport: DynHttpTransport,
    adapters: &BTreeMap<String, Arc<dyn WireAdapter>>,
) -> ProviderDescriptor {
    let models = provider_models(spec.id);
    let required_apis = models
        .iter()
        .map(|model| model.api.clone())
        .collect::<BTreeSet<_>>();
    let mut descriptor = ProviderDescriptor::new(
        spec.id,
        spec.name,
        env_auth(spec.auth_name, spec.auth_variables.iter().copied()),
        models,
    )
    .with_transport(transport);
    for api in required_apis {
        descriptor = descriptor.with_adapter(
            adapters
                .get(&api)
                .unwrap_or_else(|| panic!("missing wire adapter for generated Pi API {api}"))
                .clone(),
        );
    }
    descriptor
}

/// Concrete adapters shipped by the crate, keyed by API id.
pub fn builtin_adapters() -> BTreeMap<String, Arc<dyn WireAdapter>> {
    [
        Arc::new(AnthropicMessagesAdapter) as Arc<dyn WireAdapter>,
        Arc::new(OpenAiCompletionsAdapter),
        Arc::new(OpenAiResponsesAdapter),
        Arc::new(OpenAiCodexAdapter),
        Arc::new(AzureOpenAiResponsesAdapter::default()),
        Arc::new(GoogleGenerativeAiAdapter),
        Arc::new(GoogleVertexAdapter),
        Arc::new(MistralConversationsAdapter),
        Arc::new(BedrockConverseStreamAdapter),
        Arc::new(PiMessagesAdapter),
    ]
    .into_iter()
    .map(|adapter| (adapter.api().to_owned(), adapter))
    .collect()
}

/// Anthropic descriptor and catalog.
pub fn anthropic_provider(transport: DynHttpTransport) -> ProviderDescriptor {
    static_provider(provider_spec("anthropic"), transport)
}

/// `OpenAI` descriptor using Pi's current Responses catalog.
pub fn openai_provider(transport: DynHttpTransport) -> ProviderDescriptor {
    static_provider(provider_spec("openai"), transport)
}

/// Google Gemini API descriptor.
pub fn google_provider(transport: DynHttpTransport) -> ProviderDescriptor {
    static_provider(provider_spec("google"), transport)
}

/// Vertex descriptor for app-supplied project/location model URLs.
pub fn google_vertex_provider(
    base_url: impl Into<String>,
    mut models: Vec<Model>,
    transport: DynHttpTransport,
) -> ProviderDescriptor {
    let base_url = base_url.into();
    for model in &mut models {
        model.provider = "google-vertex".into();
        model.api = "google-vertex".into();
        model.base_url.clone_from(&base_url);
    }
    ProviderDescriptor::new(
        "google-vertex",
        "Google Vertex AI",
        env_auth(
            "Google Vertex credential",
            ["GOOGLE_VERTEX_API_KEY", "GOOGLE_VERTEX_ACCESS_TOKEN"],
        ),
        models,
    )
    .with_transport(transport)
    .with_adapter(Arc::new(GoogleVertexAdapter))
}

/// Mistral descriptor and catalog.
pub fn mistral_provider(transport: DynHttpTransport) -> ProviderDescriptor {
    static_provider(provider_spec("mistral"), transport)
}

/// Amazon Bedrock bearer-token descriptor.
pub fn bedrock_provider(transport: DynHttpTransport) -> ProviderDescriptor {
    static_provider(provider_spec("amazon-bedrock"), transport)
}

/// Azure Responses descriptor for app-supplied deployment endpoints/models.
pub fn azure_openai_provider(
    base_url: impl Into<String>,
    mut models: Vec<Model>,
    transport: DynHttpTransport,
) -> ProviderDescriptor {
    let base_url = base_url.into();
    for model in &mut models {
        model.provider = "azure-openai".into();
        model.api = "azure-openai-responses".into();
        model.base_url.clone_from(&base_url);
    }
    ProviderDescriptor::new(
        "azure-openai",
        "Azure OpenAI",
        env_auth("Azure OpenAI API key", ["AZURE_OPENAI_API_KEY"]),
        models,
    )
    .with_transport(transport)
    .with_adapter(Arc::new(AzureOpenAiResponsesAdapter::default()))
}

/// Codex Responses descriptor for app-supplied OAuth access tokens.
pub fn openai_codex_provider(
    models: Vec<Model>,
    transport: DynHttpTransport,
) -> ProviderDescriptor {
    ProviderDescriptor::new(
        "openai-codex",
        "OpenAI Codex",
        env_auth("OpenAI Codex access token", ["OPENAI_CODEX_ACCESS_TOKEN"]),
        models,
    )
    .with_transport(transport)
    .with_adapter(Arc::new(OpenAiCodexAdapter))
}

/// A focused built-in `OpenRouter` image catalog.
pub fn builtin_image_models() -> Vec<ImageModel> {
    vec![
        image_model(
            "black-forest-labs/flux.2-pro",
            "Black Forest Labs: FLUX.2 Pro",
            false,
            rates(0.0, 0.0, 0.0, 0.0),
        ),
        image_model(
            "google/gemini-2.5-flash-image",
            "Google: Nano Banana",
            true,
            rates(0.3, 2.5, 0.03, 0.083_333_333_333_333_34),
        ),
        image_model(
            "google/gemini-3-pro-image",
            "Google: Nano Banana Pro",
            true,
            rates(2.0, 12.0, 0.2, 0.375),
        ),
        image_model(
            "google/gemini-3.1-flash-image",
            "Google: Nano Banana 2",
            true,
            rates(0.5, 3.0, 0.0, 0.0),
        ),
    ]
}

fn image_model(id: &str, name: &str, text_output: bool, cost: ModelCostRates) -> ImageModel {
    ImageModel {
        id: id.into(),
        name: name.into(),
        api: "openrouter-images".into(),
        provider: "openrouter".into(),
        base_url: "https://openrouter.ai/api/v1".into(),
        input: vec![ModelInput::Text, ModelInput::Image],
        output: if text_output {
            vec![ModelInput::Image, ModelInput::Text]
        } else {
            vec![ModelInput::Image]
        },
        cost: cost.into(),
        headers: BTreeMap::new(),
    }
}

const fn rates(input: f64, output: f64, cache_read: f64, cache_write: f64) -> ModelCostRates {
    ModelCostRates {
        input,
        output,
        cache_read,
        cache_write,
    }
}

fn env_auth<'a>(name: &str, variables: impl IntoIterator<Item = &'a str>) -> ProviderAuth {
    ProviderAuth::api_key(Arc::new(EnvApiKeyAuth::new(name, variables)))
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RadiusConfig {
    base_url: String,
    models: Vec<RadiusModel>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RadiusModel {
    id: String,
    name: String,
    reasoning: bool,
    #[serde(default)]
    thinking_level_map: BTreeMap<ThinkingLevel, Option<String>>,
    input: Vec<ModelInput>,
    cost: ModelCost,
    context_window: u64,
    max_tokens: u64,
}

/// Dynamic Radius provider speaking pi-messages end-to-end.
pub struct RadiusProvider {
    id: String,
    name: String,
    gateway: String,
    auth: ProviderAuth,
    models: RwLock<Vec<Model>>,
    transport: DynHttpTransport,
    adapter: Arc<PiMessagesAdapter>,
}

impl std::fmt::Debug for RadiusProvider {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("RadiusProvider")
            .field("id", &self.id)
            .field("name", &self.name)
            .field("gateway", &self.gateway)
            .field("auth", &self.auth)
            .field("models", &self.models.read())
            .field("transport", &self.transport)
            .field("adapter", &self.adapter)
            .finish()
    }
}

impl RadiusProvider {
    /// Creates a dynamic Radius provider.
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        gateway: impl Into<String>,
        transport: DynHttpTransport,
    ) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            gateway: gateway.into().trim_end_matches('/').to_owned(),
            auth: env_auth("Radius API key", ["RADIUS_API_KEY"]),
            models: RwLock::new(Vec::new()),
            transport,
            adapter: Arc::new(PiMessagesAdapter),
        }
    }
}

#[async_trait]
impl Provider for RadiusProvider {
    fn id(&self) -> &str {
        &self.id
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn auth(&self) -> &ProviderAuth {
        &self.auth
    }

    fn models(&self) -> Vec<Model> {
        self.models.read().clone()
    }

    fn is_dynamic(&self) -> bool {
        true
    }

    async fn refresh_models(
        &self,
        auth: &AuthResult,
        options: &RefreshOptions,
    ) -> Result<(), AiError> {
        if !options.allow_network {
            return Ok(());
        }
        if options
            .cancellation
            .as_ref()
            .is_some_and(tokio_util::sync::CancellationToken::is_cancelled)
        {
            return Err(AiError::Aborted);
        }
        let url = Url::parse(&format!("{}/v1/config", self.gateway))
            .map_err(|error| AiError::Validation(error.to_string()))?;
        let mut headers = HttpHeaders::from([("accept".into(), "application/json".into())]);
        if let Some(api_key) = &auth.auth.api_key {
            headers.insert("authorization".into(), format!("Bearer {api_key}"));
        }
        for (name, value) in &auth.auth.headers {
            if let Some(value) = value {
                headers.insert(name.clone(), value.clone());
            } else {
                headers.remove(name);
            }
        }
        let response = self
            .transport
            .execute(HttpRequest {
                method: http::Method::GET,
                url,
                headers,
                body: Bytes::new(),
                timeout: None,
                cancellation: options.cancellation.clone(),
            })
            .await?;
        let config: RadiusConfig = response.json()?;
        let models = config
            .models
            .into_iter()
            .map(|entry| Model {
                id: entry.id,
                name: entry.name,
                api: "pi-messages".into(),
                provider: self.id.clone(),
                base_url: config.base_url.clone(),
                reasoning: entry.reasoning,
                thinking_level_map: entry.thinking_level_map,
                input: entry.input,
                cost: entry.cost,
                context_window: entry.context_window,
                max_tokens: entry.max_tokens,
                headers: BTreeMap::new(),
                compat: None,
            })
            .collect();
        *self.models.write() = models;
        Ok(())
    }

    fn stream(
        &self,
        model: Model,
        context: Context,
        options: WireRequestOptions,
    ) -> AssistantEventStream {
        execute_text_stream(
            self.transport.clone(),
            self.adapter.clone(),
            model,
            context,
            options,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtins_have_unique_provider_and_model_ids() {
        let providers = builtin_providers();
        let mut provider_ids = std::collections::HashSet::new();
        for provider in providers {
            assert!(provider_ids.insert(provider.id().to_owned()));
            let mut model_ids = std::collections::HashSet::new();
            for model in provider.models() {
                assert_eq!(model.provider, provider.id());
                assert!(model_ids.insert(model.id));
            }
        }
    }

    #[test]
    fn generated_catalog_matches_current_pi_snapshot() {
        let catalog = model_catalog();
        assert_eq!(catalog.len(), 37);
        assert_eq!(builtin_models().len(), 1_109);
        assert_eq!(catalog["amazon-bedrock"].len(), 114);
        assert_eq!(catalog["anthropic"].len(), 15);
        assert_eq!(catalog["openai"].len(), 38);
        assert_eq!(catalog["openai-codex"].len(), 7);
        assert_eq!(catalog["openrouter"].len(), 276);
        assert_eq!(catalog["vercel-ai-gateway"].len(), 192);
        assert!(
            catalog["openai"]
                .values()
                .all(|model| model.api == "openai-responses")
        );
    }

    #[test]
    fn adapter_catalog_covers_required_text_protocols() {
        let adapters = builtin_adapters();
        for api in [
            "anthropic-messages",
            "openai-completions",
            "openai-responses",
            "openai-codex-responses",
            "azure-openai-responses",
            "google-generative-ai",
            "google-vertex",
            "mistral-conversations",
            "bedrock-converse-stream",
            "pi-messages",
        ] {
            assert!(adapters.contains_key(api), "missing {api}");
        }
    }

    #[test]
    fn image_catalog_matches_openrouter_wire_contract() {
        let models = builtin_image_models();
        assert!(!models.is_empty());
        assert!(models.iter().all(|model| {
            model.provider == "openrouter"
                && model.api == "openrouter-images"
                && model.output.contains(&ModelInput::Image)
        }));
    }
}
