param(
    [switch] $Check
)

$workspace = Split-Path -Parent $PSScriptRoot
$reference = Join-Path $workspace 'ref/pi'
$generated = Join-Path $reference '.artifacts/model-catalog/models.json'
$snapshot = Join-Path $workspace 'crates/ri-ai/src/model_catalog.generated.json'

Push-Location $reference
try {
    npm --prefix packages/ai run generate-model-catalog
    if ($LASTEXITCODE -ne 0) {
        throw "Pi model catalog generation failed with exit code $LASTEXITCODE"
    }
}
finally {
    Pop-Location
}

if ($Check) {
    $generatedHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $generated).Hash
    $snapshotHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $snapshot).Hash
    if ($generatedHash -ne $snapshotHash) {
        throw 'Rust model catalog does not match the catalog generated by ref/pi'
    }
    Write-Output 'Rust model catalog matches ref/pi'
    exit 0
}

Copy-Item -LiteralPath $generated -Destination $snapshot -Force
Write-Output "Updated $snapshot"
